on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write
  attestations: write
  packages: write

name: release-please

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python
          package-name: tex2image

  publish:
    runs-on: ubuntu-latest
    if: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv build
      - run: uv publish --trusted-publishing always
